version: '3'

services:
  app:
    image: scratch3:12.22-alpine3.11
    build: .
    user: "node:node"
    environment:
      NODE_ENV: development
    ports:
      - 8073:8073
      - 8601:8601
    volumes:
        - ./:/usr/src/app
    tty: true
